import type { Metadata } from "next";
import "./globals.css";
import Grid from "@/components/layout/grid";

import Footer from "@/components/layout/footer";
import Nav from "@/components/layout/nav";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "개인라이브러리 아카이브",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="dark">
      <body className="bg-zinc-900 ">
        <Providers>
          <Grid>
            {" "}
            {/* nav */}
            <Nav />
            {children}
            <Footer />
          </Grid>
        </Providers>
      </body>
    </html>
  );
}
